%%%-------------------------------------------------------------------
%%% @author Tomasz Lichon
%%% @copyright (C) 2015 ACK CYFRONET AGH
%%% This software is released under the MIT license
%%% cited in 'LICENSE.txt'.
%%% @end
%%%-------------------------------------------------------------------
%%% @doc
%%% Test template generated by Intellij
%%% @end
%%%-------------------------------------------------------------------
-module(example_test).
-author("Tomasz Lichon").

-include_lib("eunit/include/eunit.hrl").

simple_test() ->
    ?assert(true).
