#!/bin/bash

#################################################################################
# Args:
# -hosts - list of hosts (i. e. -hosts localhost 123.123.123.123 )
# -keys - key pool (i. e. -keys .ssh/key1 .ssh/key2)
# -users - users to add (with groups) (i. e. -users [ name1 [ gr1 gr2 ] ] [ name2 [ gr3 ] ] )
# -uid_range - uid range for new users (i. e. -uid_range 2000 3000 )
# -gid_range - gid range for new groups (i. e. -gid_range 2000 3000 )
# -d - if defined, enables debug messages ( -d )
# Default values can be found in file /opt/oneprovider/scripts/addusers.cfg
#################################################################################

/opt/oneprovider/scripts/erl_launcher escript /opt/oneprovider/scripts/addusers.escript "$@"
