#!/bin/bash

RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)
cd $RUNNER_SCRIPT_DIR/..

reconfigure_node()
{
	sed -i "s/^main_ccm:.*/main_ccm: $MAIN_CCM/g" ./bin/config.args
	sed -i "s/^opt_ccms:.*/opt_ccms: $OPT_CCMS/g" ./bin/config.args
	sed -i "s/^db_nodes:.*/db_nodes: $DB_NODES/g" ./bin/config.args
	./bin/oneprovider
}

case "$1" in
	-restart_ccm)  	# Reconfigure and restart ccm (used when number of ccms changes)

		# Wait for the node process ( $2 ) to terminate
		while [ $(ps -p $2 | grep -c $2) -gt 0 ]; do
			sleep 1
		done

		# Wait a bit more
		sleep 1 

		# Prepare args
		MAIN_CCM=$3
		OPT_CCMS=`echo "$4" | tr ',' ' '`
		DB_NODES=`echo "$5" | tr ',' ' '`

		# Change the configuration
		reconfigure_node

		# Start the node again
		./bin/oneprovider_node start
		;;

	-restart) # Restart a node without changing configuration

		# Wait for the node process ( $2 ) to terminate
		while [ $(ps -p $2 | grep -c $2) -gt 0 ]; do
			sleep 1
		done

		# Wait a bit more
		sleep 1 

		# Start the node again
		./bin/oneprovider_node start
		;;

	-reconfigure) # Change the configuration of the node

		# Prepare args
		MAIN_CCM=$2
		OPT_CCMS=`echo "$3" | tr ',' ' '`
		DB_NODES=`echo "$4" | tr ',' ' '`

		# Change the configuration
		reconfigure_node	
		;;

	*)
		;;
esac

exit 0 