#!/bin/bash

function bad_args_error
{
	echo "Usage: "
	echo "	$0 -worker worker1@host worker2@host ... -main_ccm main_ccm_node@host [-opt_ccm opt_ccm_node1@host opt_ccm_node2@host ...]"
	echo "or"
	echo "	$0 (file 'gen_test.args' containing arguments present in script directory)"
	exit 1	
}

if [ $# -lt 4 ] || [ $1 != "-worker" ]; then

	# Check for .args file
	if [ $# -eq 0 ] && [ -f gen_dev.args ]; then
		ARGS=`cat gen_test.args`
		echo 'Using arguments from gen_test.args'
		./gen_test $ARGS
		exit 0
	fi

	# Invalid arguments or absence of .args file
	bad_args_error
fi


for (( INDEX=2; INDEX<=$#; INDEX++ ))
do
	# List ends at -main_ccm 
	if [ ${!INDEX} == "-main_ccm" ]; then
		NEXT_LOOP_INDEX=$((INDEX + 2))
		INDEX_PLUS_ONE=$((INDEX + 1))

		# Check if required main CCM name occurs
		if [ $# -lt $INDEX_PLUS_ONE ]; then
			bad_args_error
		fi
		MAIN_CCM_NAME=${!INDEX_PLUS_ONE}

		# Append main ccm to node list
		NODE_LIST[(( INDEX - 2))]=$MAIN_CCM_NAME
		break
	fi

	# Append worker to node list
	NODE_LIST[(( INDEX - 2))]=${!INDEX}
done

# If there are more arguments, but the next isn't -opt_ccm then arguments are incorrect
if [ $# -gt $NEXT_LOOP_INDEX ] && [ ${!NEXT_LOOP_INDEX} != "-opt_ccm" ]; then
	bad_args_error
fi

for (( INDEX=$((NEXT_LOOP_INDEX + 1)); INDEX<=$#; INDEX++ ))
do
	OPT_CCM_LIST="$OPT_CCM_LIST ${!INDEX}"
	NODE_LIST[(( INDEX - 4))]=${!INDEX}
done

for NODE in "${NODE_LIST[@]}"
do
	AT_INDEX=`expr index "$NODE" @`
	NODE_NAME_WITHOUT_HOSTNAME=${NODE:0:(($AT_INDEX - 1))}
	echo " "
	echo "--------------------------------------------"
	echo "generating release for $NODE in   releases/$NODE_NAME_WITHOUT_HOSTNAME"
	echo " "
	make start_config ARGS="-name $NODE -main_ccm $MAIN_CCM_NAME -opt_ccm $OPT_CCM_LIST"
	echo " "
	echo "done!"
done	

echo " "
echo "Test environment successfully set up!" 

exit 0

