# ------------------------------------------------------------------------------
# This is a configuration file for the pull-gui.sh script, for more see:
#   _build/default/lib/gui/pull-gui.sh
#
# The pull-gui.sh script fetches a GUI package (static files) and places it in
# deps directory (see pull-gui.sh -> TARGET_PATH). The package must be moved to
# the target location during release generation (usually done in rebar.config).
# The script attempts to download specified docker image from two repositories:
# docker.onedata.org (primary) or dockerhub (fallback).
# ------------------------------------------------------------------------------

# The name of the docker image containing the GUI package.
IMAGE_NAME="oneprovider-gui"
# Tag (version) of the above image.
IMAGE_TAG="ID_SHA256P-4604a7c616-ba302dbdac"
# SHA-256 checksum of the GUI package (tar.gz archive) embedded in the docker.
# Used for additional integrity check and to keep track of verified GUI packages.
PACKAGE_CHECKSUM="ba302dbdac62ea896ae74e59fadd47e036851f743c080356592b35b46ce17f80"
