# ------------------------------------------------------------------------------
# This is a configuration file for the pull-gui.sh script, for more see:
#   _build/default/lib/gui/pull-gui.sh
#
# The pull-gui.sh script fetches a GUI package (static files) and places it in
# deps directory (see pull-gui.sh -> TARGET_PATH). The package must be moved to
# the target location during release generation (usually done in rebar.config).
# The script attempts to download specified docker image from two repositories:
# docker.onedata.org (primary) or dockerhub (fallback).
# ------------------------------------------------------------------------------

# The name of the docker image containing the GUI package.
IMAGE_NAME="oneprovider-gui"
# Tag (version) of the above image.
IMAGE_TAG="ID_SHA256P-5d9c4826c7-48b6cd7600"
# SHA-256 checksum of the GUI package (tar.gz archive) embedded in the docker.
# Used for additional integrity check and to keep track of verified GUI packages.
PACKAGE_CHECKSUM="48b6cd7600d8e085d4068acc727b68d2b72ebf46e1bbdca2c0d065a764979544"
