#!/usr/bin/env bash

OUTPUT=test_dir
SUITE=multi_provider_rest_test_SUITE
TESTCASE=list_transfers
TIME_GAP=10
REPEATS=$1

rm -rf ${OUTPUT}/*
mkdir -p ${OUTPUT}

for i in $(seq 1 ${REPEATS})
do
    nohup ./ct_run.py -s ${SUITE} -c ${TESTCASE} > ${OUTPUT}/test_${i}.out &
    echo "Started test no. ${i}"
    sleep ${TIME_GAP}
done
