#!/bin/bash

## ===================================================================
## @author Krzysztof Trzepla
## @copyright (C): 2014 ACK CYFRONET AGH
## This software is released under the MIT license
## cited in 'LICENSE.txt'.
## @end
## ===================================================================
## @doc: This script copies files to RPM package and sets permissions.
## Script arguments:
## $1 - $RPM_BUILD_ROOT from SPEC file
## $2 - {_%prefix} from SPEC file
## @end
## ===================================================================

FILES=`find . -type f -exec ls {} \; 2> /dev/null`
ALL_FILES=`echo $FILES | wc -w`
N=0

for FILE in $FILES
do
	FILE=${FILE:2:${#FILE}}
	N=`expr $N + 1`
	if [[ ${FILE} == "oneprovider_init_d" ]]; then
	    	mkdir -p $1/etc/init.d
	    	install -m 0700 ${FILE} $1/etc/init.d/oneprovider
	fi
	if [[ ${FILE} == "files/onepanel_node/scripts/onepanel_init_d" ]]; then
		mkdir -p $1/etc/init.d
		install -m 0700 ${FILE} $1/etc/init.d/onepanel
	fi
	if [[ ${FILE} != `basename $0` ]]; then
		FILE_DIR=$(dirname $2/${FILE})
	    	mkdir -p $1/${FILE_DIR}
		install -m 0700 ${FILE} $1/${FILE_DIR}/
	fi
	PROGRESS=`expr $N \* 100 / $ALL_FILES`
	echo -ne "Installing files... ( $PROGRESS %)\r"
done
echo
