#!/usr/bin/env bash

## ===================================================================
## @author Krzysztof Trzepla
## @copyright (C): 2014 ACK CYFRONET AGH
## This software is released under the MIT license
## cited in 'LICENSE.txt'.
## @end
## ===================================================================
## @doc: This is a convenience script which executes
## onepanel_setup escript using erl_luncher.
## @end
## ===================================================================

/opt/veil/scripts/erl_launcher escript /opt/veil/files/onepanel/scripts/onepanel_setup.escript $@