#!/bin/bash

## ===================================================================
## @author Krzysztof Trzepla
## @copyright (C): 2014 ACK CYFRONET AGH
## This software is released under the MIT license
## cited in 'LICENSE.txt'.
## @end
## ===================================================================
## @doc: This is a convenience script which executes
## onepanel_admin escript using erl_luncher.
## @end
## ===================================================================

/opt/oneprovider/scripts/erl_launcher escript /opt/oneprovider/nodes/onepanel/scripts/onepanel_admin.escript $@