#!/bin/bash

## ===================================================================
## @author Krzysztof Trzepla
## @copyright (C): 2014 ACK CYFRONET AGH
## This software is released under the MIT license
## cited in 'LICENSE.txt'.
## @end
## ===================================================================
## @doc: This script sets up OnePanel node during oneprovider package
## post-installation hooks execution. It accepts one argument:
## * oneprovider package installation prefix
## @end
## ===================================================================

mkdir -p $1/nodes
cp -r $1/files/onepanel_node $1/nodes/onepanel
sed -i -e s/"^-name .*"/"-name onepanel@"`hostname -f`/g $1/nodes/onepanel/etc/vm.args
sed -i -e s/"^-setcookie .*"/"-setcookie oneprovider_node"/g $1/nodes/onepanel/etc/vm.args
if [ -n "$ONEPANEL_MULTICAST_ADDRESS" ]; then
    multicast_address=`echo $ONEPANEL_MULTICAST_ADDRESS | sed s/"\."/", "/g`
    sed -i -e s/"{multicast_address, [^}]*"/"{multicast_address, {$multicast_address"/g $1/nodes/onepanel/etc/app.config
fi

exit 0