#!/bin/sh
#
# chkconfig: 2345 80 30
# description: Veil service

### BEGIN INIT INFO
# Provides:		veil_init
# Required-Start:	$local_fs $remote_fs $network $time
# Required-Stop:	$local_fs $remote_fs $network $time
# Should-Start:		$syslog
# Should-Stop:		$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Veil service
# Description:	Start veil cluster nodes that are configured on this machine
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Needed for erlexec to run
export HOME=/

start() {
	start_db ; ret1=$?
	start_veil ; ret2=$?
	return `[ $ret1 -a $ret2 ]`
}

start_veil() {
	status_veil_silent ; status=$?
	if [ $status -ne 0 ]; then
		echo -n "Starting veil: "
		/opt/veil/scripts/erl_launcher escript /opt/veil/scripts/init.escript start_veil
		ret=$?
		[ $ret -eq 0 ] && success || failure
		echo
		return $ret
	fi
}
start_db() {
	status_db_silent ; status=$?
	if [ $status -ne 0 ]; then
		echo -n "Starting db: "
		/opt/veil/scripts/erl_launcher escript /opt/veil/scripts/init.escript start_db
		ret=$?
		[ $ret -eq 0 ] && success || failure
		echo
		return $ret
	fi
}

stop() {
	stop_veil ; ret1=$?
	stop_db ; ret2=$?
	return `[ $ret1 -a $ret2 ]`
}

stop_veil() {
	status_veil_silent ; status=$?
	if [ $status -eq 0 ]; then
		echo -n "Stopping veil: "
		/opt/veil/scripts/erl_launcher escript /opt/veil/scripts/init.escript stop_veil
		ret=$?
		[ $ret -eq 0 ] && success || failure
		echo
		return $ret
	fi
}
stop_db() {
	status_db_silent ; status=$?
	if [ $status -eq 0 ]; then
		echo -n "Stopping db: "
		/opt/veil/scripts/erl_launcher escript /opt/veil/scripts/init.escript stop_db
		ret=$?
		[ $ret -eq 0 ] && success || failure
		echo
		return $ret
	fi
}
restart() {
	stop
	start
}
status() {
	status_veil ; ret1=$?
    status_db ; ret2=$?
	[ $ret1 -eq 0 ] && [ $ret2 -eq 0 ] || return 3
}
status_veil() {
	status_veil_silent ; ret=$?
	[ $ret -eq 0 ] && echo "veil: Running" || echo "veil: Not running."
	return $ret
}
status_db() {
	status_db_silent ; ret=$?
	[ $ret -eq 0 ] && echo "db: Running" || echo "db: Not running."
	return $ret
}
status_veil_silent() {
	/opt/veil/scripts/erl_launcher escript /opt/veil/scripts/init.escript status_veil
}
status_db_silent() {
	/opt/veil/scripts/erl_launcher escript /opt/veil/scripts/init.escript status_db
}


case "$1" in
    start|start_veil|start_db)
		# Execute function and create a lock file (required by red-hat based systems)
		$1 && touch /var/lock/subsys/veil
		;;

	restart|force-reload)
		restart && touch /var/lock/subsys/veil
		;;

    stop|stop_veil|stop_db)
		$1
		status_veil_silent || status_db_silent || rm -f /var/lock/subsys/veil
		;;

	status|status_veil|status_db)
		$1
		;;

    *)
        echo "Usage: $0 {start|start_veil|start_db|stop|stop_veil|stop_db|restart|force-reload|status|status_veil|status_db}"
        exit 1
		;;
esac

exit $?
