#!/usr/bin/env python2

## ===================================================================
## @author Rafal Slota
## @copyright (C): 2013 ACK CYFRONET AGH
## This software is released under the MIT license
## cited in 'LICENSE.txt'.
## ===================================================================
## @doc: This script is used to merge CSV resault files generated by
##       basho_bench. The script supports summary.csv and *_latencies.csv 
##       files. See merge() call below for script arguments.
## ===================================================================

import sys

def merge(files, output):
    header = ""
    raw = []
    data = []
    for file in files:
        fh = open(file)
        lines = fh.readlines()
        raw.append(lines[1:])
        header = lines[0]
        i = 0
        for line in raw[-1]:
            new_v = [ float(x.strip()) for x in line.split(",")[2:]]
            label = [ float(x.strip()) for x in line.split(",")[:2]]
            if len(data) < i + 1:
                data.append([0.0, 0.0] + [0 for x in range(len(new_v)) ] )
            
            data[i][0] = label[0]
            data[i][1] = label[1]
            for x in range(len(new_v)):
                data[i][2 + x] = data[i][2 + x] + new_v[x]

            i = i + 1
        fh.close()
    ofh = open(output, "w")
    ofh.write(header)
    for row in data:
        if len(row) > 5:
            for x in range(3, len(row)-1):
                row[x] = row[x] / len(files)
        ofh.write(", ".join(str(x) for x in row))
        ofh.write("\n")

## All but last argumets are files to be merged into file given as last argument. 
## All files has to be with same type (summary or latencies).
merge(sys.argv[1:-1], sys.argv[-1])


