#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root"
   exit 1
fi

RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)

cd $RUNNER_SCRIPT_DIR/..

RELEASE_PACKAGE_LOCATION=/opt/oneprovider/files/oneprovider_node

START_ERL=`cat $RELEASE_PACKAGE_LOCATION/releases/start_erl.data`
ERTS_VSN=${START_ERL% *}

COMMAND=$1
shift

case $COMMAND in
	escript)
		$RELEASE_PACKAGE_LOCATION/erts-$ERTS_VSN/bin/escript "$@"
		;;

	epmd)
		$RELEASE_PACKAGE_LOCATION/erts-$ERTS_VSN/bin/epmd -daemon
		;;

	*)
		;;
esac

exit $?

