
##
## Export all variables to sub-invocation
##
export

bootstrap:
	mkdir -p $(PKG_ID)/smartos
	cd $(PKG_ID)/smartos && ../node_package/rebar -v create \
                              template_dir=../node_package/priv/templates \
                              template_vars=../$(PKG_VARS_CONFIG) template=smartos
	$(MAKE) -C $(PKG_ID) -f smartos/Makefile
