
##
## Export all variables to sub-invocation
##
export

bootstrap:
	mkdir -p $(PKG_ID)/solaris
	cd $(PKG_ID)/solaris && ../node_package/rebar -v create \
                              template_dir=../node_package/priv/templates \
                              template_vars=../$(PKG_VARS_CONFIG) template=solaris
	$(MAKE) -C $(PKG_ID) -f solaris/Makefile
