%%%-------------------------------------------------------------------
%%% @author Bartosz Walkowicz
%%% @copyright (C) 2021 ACK CYFRONET AGH
%%% This software is released under the MIT license
%%% cited in 'LICENSE.txt'.
%%% @end
%%%-------------------------------------------------------------------
%%% @doc
%%% atm_onedatafs_credentials values are generated by Oneprovider when
%%% building task execution arguments and they can't be stored/retrieved
%%% from any of the automation stores. Therefore there is no need to
%%% implement `atm_data_compressor` behaviour and validation may simply
%%% return 'ok'.
%%% @end
%%%-------------------------------------------------------------------
-module(atm_onedatafs_credentials_value).
-author("Bartosz Walkowicz").

-behaviour(atm_data_validator).

%% atm_data_validator callbacks
-export([assert_meets_constraints/3]).


%%%===================================================================
%%% atm_data_validator callbacks
%%%===================================================================


-spec assert_meets_constraints(
    atm_workflow_execution_auth:record(),
    atm_value:expanded(),
    atm_data_type:value_constraints()
) ->
    ok | no_return().
assert_meets_constraints(_AtmWorkflowExecutionAuth, _Value, _ValueConstraints) ->
    ok.
