%%%-------------------------------------------------------------------
%%% @author Bartosz Walkowicz
%%% @copyright (C) 2021 ACK CYFRONET AGH
%%% This software is released under the MIT license
%%% cited in 'LICENSE.txt'.
%%% @end
%%%-------------------------------------------------------------------
%%% @doc
%%% This module implements `atm_data_validator` functionality for
%%% `atm_onedatafs_credentials_type`. Because atm_onedatafs_credentials values
%%% are generated by Oneprovider when building task execution arguments and
%%% can't be stored/retrieved from atm stores (so there is no need to implement
%%% `atm_data_compressor` behaviour) validation may simple return 'ok'.
%%% @end
%%%-------------------------------------------------------------------
-module(atm_onedatafs_credentials_value).
-author("Bartosz Walkowicz").

-behaviour(atm_data_validator).

-include("modules/automation/atm_tmp.hrl").

%% atm_data_validator callbacks
-export([validate/3]).


%%%===================================================================
%%% atm_data_validator callbacks
%%%===================================================================


-spec validate(
    atm_workflow_execution_ctx:record(),
    atm_value:expanded(),
    atm_data_type:value_constraints()
) ->
    ok | no_return().
validate(_, Value, _ValueConstraints) when is_map(Value) ->
    ok.
