vm_arguments:

  # GENERAL
  - argument:
      name: node_name
      description: Name of the node
      value: -name nonode@nohost

  - argument:
      name: cookie
      description: Erlang cookie
      value: -setcookie oneprovider_node

  - argument:
      name: error_logger_warnings
      description: Treat error_logger warnings as warnings
      value: +W w

  - argument:
      name: erl_max_ports
      description: Increase number of concurrent ports/sockets
      value: -env ERL_MAX_PORTS 4096

  - argument:
      name: max_processes
      description: Increase number of processes
      value: +P 1000000


oneprovider_node_env:

  # GENERAL
  - parameter:
      name: developer_mode
      description: Developer mode unlocks functionalities like logging in without Global Registry
      value: false

  - parameter:
      name: trusted_openid_providers
      description: List of trusted OpenID providers that can provide user's login that can be associated with OS username.
      value: |
        ["\'plgrid\'"]
      erlang_term: |
        ['plgrid']

  # GENERAL
  - parameter:
      name: node_type
      description: Node type (worker or ccm)
      value: ccm

  - parameter:
      name: ccm_nodes
      description: List of possible ccm nodes
      value: |
        ["\'ccm1@127.0.0.1\'"]
      erlang_term: |
        ['ccm1@127.0.0.1']

  - parameter:
      name: db_nodes
      description: List of all DBMS nodes
      value: |
        ["\'db1@127.0.0.1\'"]
      erlang_term: |
        ['db1@127.0.0.1']

  - parameter:
      name: storage_config_path
      description: Path to storage config file
      value: |
        "\'/opt/oneprovider/worker/bin/storage_info.cfg\'"
      erlang_term: "'/opt/oneprovider/nodes/worker/bin/storage_info.cfg'"

  - parameter:
      name: initialization_time
      description: How long should ccm wait for workers before it initializes cluster
      value: 10

  - parameter:
      name: callback_ack_time
      description: After callback_ack_time node_manager stops waiting for ack
      value: 60

  - parameter:
      name: heart_beat
      description: How long (in sec) should worker sleep before next connection try (when it cannot connect to ccm)
      value: 60

  - parameter:
      name: worker_load_memory_size
      description: Memory size which stores information about worker load
      value: 1000

  - parameter:
      name: web_ssl_cert_path
      description: Path to certificate used by ranch_ssl in gui handler
      value: |
        "\'./certs/onedataServerWeb.pem\'"
      erlang_term: "'./certs/onedataServerWeb.pem'"
      # this has to be in double quotes so that single quotes are preserved after
      # conversion to list and it ends up correct in app.src

  - parameter:
      name: fuse_ssl_cert_path
      description: Path to certificate used by ranch_ssl in fuse clients handler
      value: |
        "\'./certs/onedataServerFuse.pem\'"
      erlang_term: "'./certs/onedataServerFuse.pem'"
      # this has to be in double quotes so that single quotes are preserved after
      # conversion to list and it ends up correct in app.src

  - parameter:
      name: fslogic_cleaning_period
      description: How often fslogic should clean not used descriptors
      value: 600

  - parameter:
      name: user_files_size_view_update_period
      description: How often (in seconds) fslogic should update view counting user's files size
      value: 60 # 1 min

  - parameter:
      name: cluster_monitoring_period
      description: How often should central cluster manager wait between successive checks of node status
      value: 60

  - parameter:
      name: cluster_monitoring_initialization
      description: How long (in seconds) cluster manager should wait before it starts monitoring
      value: 30

  - parameter:
      name: node_monitoring_period
      description: How often should node manager wait between successive checks of node status
      value: 10

  - parameter:
      name: node_monitoring_initialization
      description: How long (in seconds) node manager should wait before it starts monitoring
      value: 10

  - parameter:
      name: node_load_logging_period
      description: How often (in seconds) should load of each node be logged
      value: 10

  - parameter:
      name: delete_storage_test_file_time
      description: After delete_storage_test_file_time seconds storage test file will be deleted
      value: 60

  - parameter:
      name: short_monitoring_time_window
      description: Short time window (in seconds) for which Round Robin Database will be queried
      value: 60

  - parameter:
      name: medium_monitoring_time_window
      description: Medium time window (in seconds) for which Round Robin Database will be queried
      value: 300

  - parameter:
      name: long_monitoring_time_window
      description: Long time window (in seconds) for which Round Robin Database will be queried
      value: 900

  - parameter:
      name: nif_prefix
      description: Prefix to c_lib directory containing NIF libs
      value: |
          "\'.\'"
      erlang_term: "'.'"

  - parameter:
      name: ports_in_use
      description: Ports used by application, that need to be free before oneprovider node can start
      value: |
          ["control_panel_port","control_panel_redirect_port","dns_port","dispatcher_port","rest_port"]
      erlang_term: |
          [control_panel_port,control_panel_redirect_port,dns_port,dispatcher_port,rest_port]

  - parameter:
      name: storage_config_name
      description: Name of storage configuration file used by client during automatic storage detection
      value: |
          "\'vfs_storage.info\'"
      erlang_term: "'vfs_storage.info'"

  # RRDERLANG
  - parameter:
      name: rrd_timeout
      description: Time in ms after which rrderlang answers with error
      value: 5000

  - parameter:
      name: rrd_size
      description: Defines how many primary data points - divided by monitoring period - are collected
      value: 7200

  - parameter:
      name: rrd_steps
      description: Defines how many primary data points are used to build a consolidated data point which then goes into the archive
      value: |
          ["1","24","168","720","8760"] # 1 hour, 1 day, 7 days, 30 days, 365 days
      erlang_term: |
          [1,24,168,720,8760]


  # DISPATCHER
  - parameter:
      name: dispatcher_pool_size
      description: Number of threads used by dispatcher
      value: 1000

  - parameter:
      name: dispatcher_port
      description: Number of port used by dispatcher
      value: 5555

  - parameter:
      name: ranch_timeout
      description: Time in ms after witch ranch kills thread that does nothing
      value: 5000

  - parameter:
      name: dispatcher_timeout
      description: Time in ms after witch ranch answers with error
      value: 120000

  - parameter:
      name: ca_dir
      description: path to dir containing CA and CRL certs used by GSI handler
      value: cacerts

  - parameter:
      name: certs_dir
      description: path to dir containing server certs used by GSI handler
      value: certs

  - parameter:
      name: crl_update_interval
      description: the interval between CRL updates done by GSI handler
      value: 3600000


  # CONTROL PANEL
  - parameter:
      name: control_panel_port
      description: Port on which control_panel is available
      value: 443

  - parameter:
      name: control_panel_redirect_port
      description: Port on which standard HTTP will be opened to redirect requests to HTTPS
      value: 80

  - parameter:
      name: rest_port
      description: Port on which REST API is available
      value: 8443

  - parameter:
      name: control_panel_static_files_root
      description: Directory in release where static gui files are stored
      value: |
        "\'./gui_static\'"
      erlang_term: "'./gui_static'"

  - parameter:
      name: control_panel_number_of_acceptors
      description: Number of accepting processes in control_panel listener
      value: 100

  - parameter:
      name: control_panel_number_of_http_acceptors
      description: Number of accepting processes on port 80 (redirecting to https)
      value: 50

  - parameter:
      name: control_panel_max_keepalive
      description: Maximum number of HTTP requests without closing the connection (HTTP/1.1 only)
      value: 30
      # This is used only by n2o GUI. REST, HTTP on port 80 and upload handler all have max_keepalive = 1

  - parameter:
      name: control_panel_socket_timeout
      description: Socket timeout in ms
      value: 60000

  - parameter:
      name: nagios_healtcheck_timeout
      description: Time for healtcheck response
      value: 2000

  - parameter:
      name: multipart_max_length
      description: Maximum post body size for a file upload (data/multipart) in Bytes
      value: 107374182400 # 100GB

  - parameter:
      name: control_panel_download_buffer
      description: Buffer size used to send file to a client
      value: 1048576

  - parameter:
      name: control_panel_upload_buffer
      description: Buffer size used to stream file from a client
      value: 1048576

  - parameter:
      name: control_panel_sessions_clearing_period
      description: Period between automatic deletion of expired session tokens, in seconds.
      value: 7200 # two hours

  - parameter:
      name: control_panel_sessions_cookie_ttl
      description: Cookies time to live - expiration date will be set this many seconds from time of creation (in seconds).
      value: 3600 # one hour


  # Global Registry interfacing
  - parameter:
      name: global_registry_provider_key_path
      description: Path to .pem file containing the private key to the grpcert.
      value: |
        "\'certs/grpkey.pem\'"
      erlang_term: "'certs/grpkey.pem'"
      
  - parameter:
      name: global_registry_provider_cert_path
      description: Path to .pem file containing the certificate signed by Global Registry CA, used for authorizing requests to it.
      value: |
        "\'certs/grpcert.pem\'"
      erlang_term: "'certs/grpcert.pem'"
      
  - parameter:
      name: global_registry_ca_cert_path
      description: Path to .pem file containing the Global Registry CA certificate.
      value: |
        "\'cacerts/grpCA.pem\'"
      erlang_term: "'cacerts/grpCA.pem'"

  - parameter:
      name: global_registry_hostname
      description: Global Registry hostname.
      value: |
        "\'https://onedata.org\'"
      erlang_term: "'https://onedata.org'"

  - parameter:
      name: global_registry_url
      description: Global Registry REST API endpoint URL.
      value: |
        "\'https://onedata.org:8443\'"
      erlang_term: "'https://onedata.org:8443'"

  # Files management
  - parameter:
      name: new_file_logic_mode
      description: Default mode for new file (mode stored in db) (8#600)
      value: 384

  - parameter:
      name: new_group_file_logic_mode
      description: Default mode for new file (mode stored in db) inside groups directory (8#640)
      value: 416

  - parameter:
      name: new_file_storage_mode
      description: Default mode for new file at storage system (8#600)
      value: 384

  - parameter:
      name: new_group_file_storage_mode
      description: Default mode for new file at storage system inside groups directory (8#640)
      value: 416

  - parameter:
      name: new_dir_storage_mode
      description: Default mode for new directory at storage system (8#1330)
      value: 728

  - parameter:
      name: lowest_generated_storage_gid
      description: Lowest GID used for files that shall belong to group that doesn't exist in OS.
      value: 70000

  - parameter:
        name: provider_proxy_block_size
        description: Block size for inter-provider file read/write operation
        value: 1048576 # 1MB


  # DNS
  - parameter:
      name: dns_response_ttl
      description: How long dns response remains valid (in sec)
      value: 60

  - parameter:
      name: dns_tcp_acceptor_pool_size
      description: Number of dns tcp acceptors
      value: 50

  - parameter:
      name: dns_tcp_timeout
      description: Time (in sec) after which dns closes idle connection
      value: 30

  - parameter:
      name: dns_port
      description: DNS port
      value: 53



  # DAO
  - parameter:
      name: fuse_session_expire_time
      description: |
        This variable determinates how often FUSE sessions shall be checked (in seconds).
        Note that session will be discarded only when there are no connections active for the session.
      value: 10800 # 3h

  - parameter:
       name: dao_fuse_cache_loop_time
       description: |
         This variable determinates how often DAO fuse cache maintnance process shall fire up all its jobs (in seconds).
       value: 1800 # 30min

  - parameter:
       name: storage_cache_loop_time
       description: |
         This variable determinates how often DAO storage cache should be cleared (in seconds).
       value: 86400 # 24h

  - parameter:
       name: users_cache_loop_time
       description: |
         This variable determinates how often DAO storage cache should be cleared (in seconds).
       value: 86400 # 24h

  - parameter:
      name: io_bytes_threshold
      description: |
           Defines how often io event is generated in terms of read or written bytes.
      value: 1048576 # 1MB

  - parameter:
      name: view_def_location
      description: Location of database views definitions.
      value: |
        "\'views/\'"
      erlang_term: "'views/'"

  # Quota management
  - parameter:
      name: default_quota
      description: |
        This variable will be used to determine user quota if property size of quota doc of user has not been changed after user creation.
        By default user quota is saved in db per user as special value indicating that default_quota should be used.
        So if you change this value it will be applied to all users (existing and those that will be created in future) except of those whose quota has been manually changed.
      value: 10737418240 # 10GB

  - parameter:
      name: quota_check_freq
      description: |
        This variable determines after how many bytes written quota check is performed.
      value: 10485760 # 10MB

obsolete:
  - parameter:
      description: |
        Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
        (Disabled by default..use with caution!)
      name: heart
      value: -heart

  - parameter:
      description: Enable kernel poll and a few async threads
      name: kernel_pool_async_threads
      value: |
        +K true
        +A 5

  - parameter:
      description: Tweak GC to run more often
      name: erl_fullsweep_after
      value: -env ERL_FULLSWEEP_AFTER 10
