veil::client::FslogicProxy
boost::shared_ptr<MessageBuilder> veil::client::FslogicProxy::m_messageBuilder
MessageBuilder used to construct cluster packets.
Referenced by sendFuseReceiveAnswer, sendFuseReceiveAtom.
bool veil::client::FslogicProxy::sendFuseReceiveAnswer(const google::protobuf::Message &fMsg, google::protobuf::Message &response)
Sends and receives given protobuf message.
High level method used to send serialized protobuf message to cluster and return its response as given by reference object. Both message and response types have to be subtype of FuseMessage. true only if received response message is initialized (see google::protobuff::Message::IsInitialized())
References m_messageBuilder, FUSE_MESSAGES, veil::client::VeilFS::getConnectionPool.
Referenced by getFileAttr, getFileLocation, getNewFileLocation, renewFileLocation, getFileChildren, getLink.
string veil::client::FslogicProxy::sendFuseReceiveAtom(const google::protobuf::Message &fMsg)
Sends given protobuf message and receives atom.
This method is simalar to FslogicProxy::sendFuseReceiveAnswer But receives simple atom cluster response. FslogicProxy::sendFuseReceiveAnswer
References m_messageBuilder, COMMUNICATION_PROTOCOL, veil::client::VeilFS::getConnectionPool.
Referenced by createDir, deleteFile, sendFileNotUsed, renameFile, changeFilePerms, updateTimes, changeFileOwner, changeFileGroup, createLink.
veil::client::FslogicProxy::FslogicProxy()
veil::client::FslogicProxy::~FslogicProxy()
bool veil::client::FslogicProxy::getFileAttr(std::string logicName, protocol::fuse_messages::FileAttr &attr)
Downloads file attributes from cluster.
References sendFuseReceiveAnswer.
bool veil::client::FslogicProxy::getFileLocation(std::string logicName, protocol::fuse_messages::FileLocation &location)
Downloads file location info.
References sendFuseReceiveAnswer.
bool veil::client::FslogicProxy::getNewFileLocation(std::string logicName, mode_t mode, protocol::fuse_messages::FileLocation &location)
Query cluser to create new file in DB and get its real location.
References sendFuseReceiveAnswer.
int veil::client::FslogicProxy::renewFileLocation(std::string logicName)
Try to renew location validity for given file.
References sendFuseReceiveAnswer.
bool veil::client::FslogicProxy::getFileChildren(std::string dirLogicName, uint32_t children_num, uint32_t offset, std::vector< std::string > &childrenNames)
List files in given folder.
References sendFuseReceiveAnswer.
string veil::client::FslogicProxy::renameFile(std::string fromLogicName, std::string toLogicName)
Rename/move file to new location.
References sendFuseReceiveAtom.
string veil::client::FslogicProxy::createDir(std::string logicName, mode_t mode)
Create directory.
References sendFuseReceiveAtom.
string veil::client::FslogicProxy::deleteFile(std::string logicName)
Delete given file.
References sendFuseReceiveAtom.
bool veil::client::FslogicProxy::sendFileNotUsed(std::string logicName)
Inform cluster that file isnt used anymore.
References sendFuseReceiveAtom.
Referenced by runTask.
string veil::client::FslogicProxy::changeFilePerms(std::string path, mode_t mode)
Change file permissions.
References sendFuseReceiveAtom.
string veil::client::FslogicProxy::createLink(std::string from, std::string to)
Creates symbolic link "from" to file "to".
References sendFuseReceiveAtom.
pair< string, string > veil::client::FslogicProxy::getLink(std::string path)
Gets path pointed by link.
References sendFuseReceiveAnswer.
string veil::client::FslogicProxy::updateTimes(std::string path, time_t atime=0, time_t mtime=0, time_t ctime=0)
Updates *time meta attributes for specific file.
References sendFuseReceiveAtom.
string veil::client::FslogicProxy::changeFileOwner(std::string path, uid_t uid, std::string uname="")
Updates file's owner.
References sendFuseReceiveAtom.
string veil::client::FslogicProxy::changeFileGroup(std::string path, gid_t gid, std::string gname="")
Updates file's group owner.
References sendFuseReceiveAtom.
void veil::client::FslogicProxy::pingCluster(std::string)
References PROTOCOL_VERSION, FSLOGIC, ATOM, COMMUNICATION_PROTOCOL, veil::client::VeilFS::getConnectionPool, veil::client::VeilFS::getConfig, CLUSTER_PING_INTERVAL_OPT, veil::client::ISchedulable::TASK_PING_CLUSTER, veil::client::VeilFS::getScheduler.
Referenced by runTask.
bool veil::client::FslogicProxy::runTask(TaskID taskId, std::string arg0, std::string arg1, std::string arg3)
Task runner derived from ISchedulable.
ISchedulable::runTask
References veil::client::ISchedulable::TASK_SEND_FILE_NOT_USED, sendFileNotUsed, veil::client::ISchedulable::TASK_PING_CLUSTER, pingCluster.