veil::client::JobScheduler
std::priority_queue<Job> veil::client::JobScheduler::m_jobQueue
Run queue.
Referenced by schedulerMain, addTask, deleteJobs, hasTask.
pthread_t veil::client::JobScheduler::m_daemon
Thread ID.
Referenced by ~JobScheduler, startDaemon.
pthread_mutex_t veil::client::JobScheduler::m_mutex
Mutex used to synchronize access to JobScheduler::m_jobQueue.
Referenced by startDaemon, schedulerMain, addTask, deleteJobs, hasTask.
pthread_cond_t veil::client::JobScheduler::m_queueCond
Condition used to synchronize access to JobScheduler::m_jobQueue.
Referenced by startDaemon, schedulerMain, addTask.
void veil::client::JobScheduler::schedulerMain()
Thread main loop.
Checks run queue and runs tasks when needed.
References PTHREAD_CMD, m_mutex, m_jobQueue, m_queueCond, runJob.
void veil::client::JobScheduler::runJob(Job job)
Starts given task.
JobScheduler::schedulerMain
References veil::client::Job::task, veil::client::Job::arg0, veil::client::Job::arg1, veil::client::Job::arg2, veil::client::Job::subject.
Referenced by schedulerMain.
void veil::client::JobScheduler::startDaemon()
Starts/restarts daemon.
References m_mutex, m_queueCond, m_daemon, schedulerMainWrapper.
Referenced by JobScheduler.
void * veil::client::JobScheduler::schedulerMainWrapper(void *arg)
C wrapper used to start JobScheduler::schedulerMain.
Referenced by startDaemon.
veil::client::JobScheduler::JobScheduler()
References startDaemon.
veil::client::JobScheduler::~JobScheduler()
References m_daemon.
bool veil::client::JobScheduler::hasTask(ISchedulable::TaskID task)
References veil::client::ISchedulable::TASK_LAST_ID, m_mutex, m_jobQueue, veil::client::Job::task.
void veil::client::JobScheduler::addTask(Job job)
Insert (register) new task to run queue.
Inserted task shall run when current time passes its Job::when. ::Job
References m_mutex, veil::client::Job::task, m_jobQueue, PTHREAD_CMD, m_queueCond.
void veil::client::JobScheduler::deleteJobs(ISchedulable *subject, ISchedulable::TaskID task)
Deletes all jobs registred by given object.
Used mainly when ISchedulable object is destructed.
References m_mutex, m_jobQueue, veil::client::Job::subject, veil::client::Job::task, veil::client::ISchedulable::TASK_LAST_ID.