veil::client::AutoLock
ReadWriteLock& veil::client::AutoLock::m_lock
The wrapped lock.
Referenced by changeType, release, lock.
LockType veil::client::AutoLock::m_type
Type of this lock.
LockType
Referenced by changeType, release, lock.
bool veil::client::AutoLock::m_released
Flag saying if lock is released right now.
Referenced by release, lock.
veil::client::AutoLock::AutoLock(ReadWriteLock &lock, LockType type)
Create auto ReadWriteLock.
Also locks for read/write depending on LockType param.
References lock.
veil::client::AutoLock::~AutoLock()
Unlocks wrapped ReadWriteLock lock, but only if it wasn't released manually.
References release.
void veil::client::AutoLock::changeType(LockType type)
Changle lock type.
Releases current lock and locks for diffrent operation type.
References veil::client::READ_LOCK, m_type, veil::client::WRITE_LOCK, m_lock, veil::client::ReadWriteLock::writeUnlock, veil::client::ReadWriteLock::readLock, veil::client::ReadWriteLock::readUnlock, veil::client::ReadWriteLock::writeLock.
Referenced by veil::client::VeilFS::readlink.
void veil::client::AutoLock::release()
Release current lock.
References m_released, m_type, veil::client::READ_LOCK, m_lock, veil::client::ReadWriteLock::readUnlock, veil::client::ReadWriteLock::writeUnlock.
Referenced by ~AutoLock, veil::client::StorageMapper::getLocationInfo.
void veil::client::AutoLock::lock()
Locks current lock.
References m_released, m_type, veil::client::READ_LOCK, m_lock, veil::client::ReadWriteLock::readLock, veil::client::ReadWriteLock::writeLock.
Referenced by AutoLock, veil::client::StorageMapper::getLocationInfo.