veil::client::VeilFS
std::string veil::client::VeilFS::m_root
Filesystem root directory.
Referenced by VeilFS, readlink, symlink.
uid_t veil::client::VeilFS::m_uid
Filesystem owner's effective uid.
Referenced by VeilFS, getattr.
gid_t veil::client::VeilFS::m_gid
Filesystem owner's effective gid.
Referenced by VeilFS, getattr.
uid_t veil::client::VeilFS::m_ruid
Filesystem root real uid.
Referenced by VeilFS, getattr.
gid_t veil::client::VeilFS::m_rgid
Filesystem root real gid.
Referenced by VeilFS, getattr.
boost::shared_ptr<FslogicProxy> veil::client::VeilFS::m_fslogic
FslogicProxy instance.
Referenced by VeilFS, getattr, readlink, mknod, mkdir, unlink, rmdir, symlink, rename, chmod, chown, readdir, runTask.
boost::shared_ptr<StorageMapper> veil::client::VeilFS::m_storageMapper
StorageMapper instance.
Referenced by getattr, mknod, open, release.
boost::shared_ptr<MetaCache> veil::client::VeilFS::m_metaCache
MetaCache instance.
Referenced by getattr, mknod, mkdir, unlink, rmdir, rename, chmod, chown, truncate, write, runTask.
boost::shared_ptr<helpers::StorageHelperFactory> veil::client::VeilFS::m_shFactory
Storage Helpers Factory instance.
std::map<std::string, std::pair<std::string, time_t> > veil::client::VeilFS::m_linkCache
Simple links cache.
Referenced by getattr, readlink.
ReadWriteLock veil::client::VeilFS::m_linkCacheLock
Referenced by getattr, readlink.
ReadWriteLock veil::client::VeilFS::m_schedulerPoolLock
Referenced by getScheduler, addScheduler.
list< boost::shared_ptr< JobScheduler > > veil::client::VeilFS::m_jobSchedulers
JobScheduler instances.
Referenced by staticDestroy, getScheduler, addScheduler.
boost::shared_ptr< Config > veil::client::VeilFS::m_config
Config instance.
Referenced by VeilFS, staticDestroy, getConfig, setConfig.
boost::shared_ptr< SimpleConnectionPool > veil::client::VeilFS::m_connectionPool
Referenced by staticDestroy, getConnectionPool, setConnectionPool.
boost::shared_ptr< PushListener > veil::client::VeilFS::m_pushListener
Referenced by VeilFS, staticDestroy, getPushListener.
boost::shared_ptr< JobScheduler > veil::client::VeilFS::getScheduler(TaskID taskId=TASK_LAST_ID)
Returns JobScheduler assigned to this object.
References m_schedulerPoolLock, veil::client::WRITE_LOCK, m_jobSchedulers.
Referenced by veil::client::FslogicProxy::pingCluster, veil::client::StorageMapper::addLocation, veil::client::StorageMapper::releaseFile, veil::client::StorageMapper::runTask, VeilFS, getattr, mknod, mkdir, unlink, rmdir, rename, utime, open, write, opendir, readdir, runTask.
boost::shared_ptr< Config > veil::client::VeilFS::getConfig()
Returns Config assigned to this object.
References m_config.
Referenced by veil::client::FslogicProxy::pingCluster, veil::client::PushListener::onChannelError, VeilFS, getattr, readdir, runTask.
boost::shared_ptr< SimpleConnectionPool > veil::client::VeilFS::getConnectionPool()
References m_connectionPool.
Referenced by veil::client::FslogicProxy::sendFuseReceiveAnswer, veil::client::FslogicProxy::sendFuseReceiveAtom, veil::client::FslogicProxy::pingCluster.
boost::shared_ptr< PushListener > veil::client::VeilFS::getPushListener()
References m_pushListener.
void veil::client::VeilFS::addScheduler(boost::shared_ptr< JobScheduler > injected)
Sets JobScheduler object.
References m_schedulerPoolLock, veil::client::WRITE_LOCK, m_jobSchedulers.
Referenced by VeilFS.
void veil::client::VeilFS::setConfig(boost::shared_ptr< Config > injected)
Sets Config object.
References m_config.
void veil::client::VeilFS::setConnectionPool(boost::shared_ptr< SimpleConnectionPool > injected)
References m_connectionPool.
void veil::client::VeilFS::staticDestroy()
References m_config, m_jobSchedulers, m_connectionPool, m_pushListener.
veil::client::VeilFS::VeilFS(std::string path, boost::shared_ptr< Config > cnf, boost::shared_ptr< JobScheduler > scheduler, boost::shared_ptr< FslogicProxy > fslogic, boost::shared_ptr< MetaCache > metaCache, boost::shared_ptr< StorageMapper > mapper, boost::shared_ptr< helpers::StorageHelperFactory > sh_factory)
VeilFS constructor.
References m_root, m_config, addScheduler, m_pushListener, getConfig, m_fslogic, getScheduler, ALIVE_META_CONNECTIONS_COUNT_OPT, veil::client::ISchedulable::TASK_PING_CLUSTER, m_uid, m_gid, m_ruid, m_rgid.
veil::client::VeilFS::~VeilFS()
int veil::client::VeilFS::access(const char *path, int mask)
access FUSE callback.
Not implemented yet.
int veil::client::VeilFS::getattr(const char *path, struct stat *statbuf, bool fuse_ctx=true)
getattr FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_metaCache, m_fslogic, m_storageMapper, veil::client::ISchedulable::TASK_ASYNC_GET_FILE_LOCATION, getScheduler, m_ruid, m_rgid, m_uid, m_gid, getConfig, ENABLE_DIR_PREFETCH_OPT, ENABLE_ATTR_CACHE_OPT, veil::client::ISchedulable::TASK_ASYNC_READDIR, m_linkCacheLock, veil::client::WRITE_LOCK, m_linkCache.
Referenced by runTask.
int veil::client::VeilFS::readlink(const char *path, char *link, size_t size)
readlink FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_linkCacheLock, veil::client::READ_LOCK, m_linkCache, m_fslogic, RETURN_IF_ERROR, veil::client::AutoLock::changeType, veil::client::WRITE_LOCK, m_root.
int veil::client::VeilFS::mknod(const char *path, mode_t mode, dev_t dev)
mknod FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_metaCache, m_fslogic, m_storageMapper, GET_LOCATION_INFO, SH_RUN, getScheduler, veil::client::ISchedulable::TASK_CLEAR_ATTR, PARENT.
int veil::client::VeilFS::mkdir(const char *path, mode_t mode)
mkdir FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_metaCache, RETURN_IF_ERROR, m_fslogic, getScheduler, veil::client::ISchedulable::TASK_CLEAR_ATTR, PARENT.
int veil::client::VeilFS::unlink(const char *path)
unlink FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_metaCache, m_fslogic, GET_LOCATION_INFO, SH_RUN, RETURN_IF_ERROR, getScheduler, veil::client::ISchedulable::TASK_CLEAR_ATTR, PARENT.
int veil::client::VeilFS::rmdir(const char *path)
rmdir FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_metaCache, RETURN_IF_ERROR, m_fslogic, getScheduler, veil::client::ISchedulable::TASK_CLEAR_ATTR, PARENT.
int veil::client::VeilFS::symlink(const char *path, const char *link)
symlink FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_root, RETURN_IF_ERROR, m_fslogic.
int veil::client::VeilFS::rename(const char *path, const char *newpath)
rename FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References RETURN_IF_ERROR, m_fslogic, getScheduler, veil::client::ISchedulable::TASK_CLEAR_ATTR, PARENT, m_metaCache.
int veil::client::VeilFS::link(const char *path, const char *newpath)
link FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::chmod(const char *path, mode_t mode)
chmod FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References RETURN_IF_ERROR, m_fslogic, m_metaCache, GET_LOCATION_INFO, SH_RUN.
int veil::client::VeilFS::chown(const char *path, uid_t uid, gid_t gid)
chown FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_metaCache, RETURN_IF_ERROR, m_fslogic.
int veil::client::VeilFS::truncate(const char *path, off_t newSize)
truncate FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References GET_LOCATION_INFO, SH_RUN, m_metaCache.
int veil::client::VeilFS::utime(const char *path, struct utimbuf *ubuf)
utime FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References getScheduler, veil::client::ISchedulable::TASK_ASYNC_UPDATE_TIMES, veil::client::utils::toString.
int veil::client::VeilFS::open(const char *path, struct fuse_file_info *fileInfo)
open FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References GET_LOCATION_INFO, m_storageMapper, SH_RUN, getScheduler, veil::client::ISchedulable::TASK_ASYNC_UPDATE_TIMES, veil::client::utils::toString.
int veil::client::VeilFS::read(const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fileInfo)
read FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References GET_LOCATION_INFO, SH_RUN.
int veil::client::VeilFS::write(const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *fileInfo)
write FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References GET_LOCATION_INFO, SH_RUN, m_metaCache, getScheduler, veil::client::ISchedulable::TASK_CLEAR_ATTR.
int veil::client::VeilFS::statfs(const char *path, struct statvfs *statInfo)
statfs FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::flush(const char *path, struct fuse_file_info *fileInfo)
flush FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::release(const char *path, struct fuse_file_info *fileInfo)
release FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_storageMapper.
int veil::client::VeilFS::fsync(const char *path, int datasync, struct fuse_file_info *fi)
fsync FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::setxattr(const char *path, const char *name, const char *value, size_t size, int flags)
setxattr FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::getxattr(const char *path, const char *name, char *value, size_t size)
getxattr FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::listxattr(const char *path, char *list, size_t size)
listxattr FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::removexattr(const char *path, const char *name)
removexattr FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::opendir(const char *path, struct fuse_file_info *fileInfo)
opendir FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References getScheduler, veil::client::ISchedulable::TASK_ASYNC_UPDATE_TIMES, veil::client::utils::toString.
int veil::client::VeilFS::readdir(const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fileInfo)
readdir FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
References m_fslogic, DIR_BATCH_SIZE, getConfig, ENABLE_PARALLEL_GETATTR_OPT, ENABLE_ATTR_CACHE_OPT, veil::client::ISchedulable::TASK_ASYNC_GETATTR, getScheduler.
int veil::client::VeilFS::releasedir(const char *path, struct fuse_file_info *fileInfo)
releasedir FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::fsyncdir(const char *path, int datasync, struct fuse_file_info *fileInfo)
fsyncdir FUSE callback.
Not implemented yet. http://fuse.sourceforge.net/doxygen/structfuse__operations.html
int veil::client::VeilFS::init(struct fuse_conn_info *conn)
init FUSE callback.
http://fuse.sourceforge.net/doxygen/structfuse__operations.html
bool veil::client::VeilFS::runTask(TaskID taskId, std::string arg0, std::string arg1, std::string arg3)
Task runner derived from ISchedulable.
ISchedulable::runTask
References veil::client::ISchedulable::TASK_ASYNC_READDIR, getConfig, ENABLE_ATTR_CACHE_OPT, m_fslogic, DIR_BATCH_SIZE, veil::client::ISchedulable::TASK_ASYNC_GETATTR, getScheduler, veil::client::utils::toString, veil::client::ISchedulable::TASK_CLEAR_ATTR, m_metaCache, getattr, veil::client::ISchedulable::TASK_ASYNC_UPDATE_TIMES.