veil::client::ReadWriteLock
pthread_cond_t veil::client::ReadWriteLock::m_classCond
Referenced by ReadWriteLock, readLock, readUnlock, writeLock, writeUnlock.
int veil::client::ReadWriteLock::m_readers
How many readers are in critical section right now.
Referenced by readLock, readUnlock, writeLock.
int veil::client::ReadWriteLock::m_writers
How many writers are waitning in queue to access critical section.
Referenced by readLock, writeLock.
int veil::client::ReadWriteLock::m_fairness
How many readers was in critical section since last writer left.
Referenced by readLock, writeUnlock.
veil::client::ReadWriteLock::DECLARE_MUTEX_FOR(m_class)
veil::client::ReadWriteLock::DECLARE_MUTEX_FOR(m_res)
veil::client::ReadWriteLock::ReadWriteLock()
References INIT_MUTEX_FOR, m_classCond.
veil::client::ReadWriteLock::~ReadWriteLock()
void veil::client::ReadWriteLock::readLock()
Locks for read operation.
References MUTEX, m_writers, m_fairness, FAIRNESS_LEVEL, m_classCond, m_readers.
Referenced by veil::client::AutoLock::changeType, veil::client::AutoLock::lock.
void veil::client::ReadWriteLock::readUnlock()
Unlocks read lock.
References MUTEX, m_readers, m_classCond.
Referenced by veil::client::AutoLock::changeType, veil::client::AutoLock::release.
void veil::client::ReadWriteLock::writeLock()
Locks for write operation.
References MUTEX, m_writers, m_readers, m_classCond.
Referenced by veil::client::AutoLock::changeType, veil::client::AutoLock::lock.
void veil::client::ReadWriteLock::writeUnlock()
< Unlocks write lock
References m_fairness, m_classCond, MUTEX.
Referenced by veil::client::AutoLock::changeType, veil::client::AutoLock::release.