veil::client::StorageMapper
std::map<int, storageInfo> veil::client::StorageMapper::m_storageMapping
Contains storage info accessd by its ID.
storageInfo
Referenced by getLocationInfo, addLocation.
ReadWriteLock veil::client::StorageMapper::m_storageMappingLock
Lock used while operating on StorageMapper::m_storageMapping.
StorageMapper::m_storageMapping
Referenced by getLocationInfo, addLocation.
std::map<std::string, locationInfo> veil::client::StorageMapper::m_fileMapping
Contains storage info accessd by its ID.
storageInfo
Referenced by getLocationInfo, addLocation, openFile, releaseFile, runTask.
ReadWriteLock veil::client::StorageMapper::m_fileMappingLock
Lock used while operationg on StorageMapper::m_fileMapping.
StorageMapper::m_fileMapping
Referenced by getLocationInfo, addLocation, openFile, releaseFile, runTask.
boost::shared_ptr<FslogicProxy> veil::client::StorageMapper::m_fslogic
Reference to FslogicProxy instance.
VeilFS::m_fslogic
Referenced by findLocation, releaseFile, runTask.
veil::client::StorageMapper::StorageMapper(boost::shared_ptr< FslogicProxy > fslogicProxy)
veil::client::StorageMapper::~StorageMapper()
pair< locationInfo, storageInfo > veil::client::StorageMapper::getLocationInfo(std::string logical_name, bool useCluster=false)
Gets file location information along with storage info for storage heleper's calls.
logical_name File path (relative to VeilFS mount point) useCluster Specify if the method should use cache only (deafault) or try quering cluster. std::pair of locationInfo and storageInfo structs for this file
References m_fileMappingLock, veil::client::READ_LOCK, m_fileMapping, veil::client::AutoLock::release, findLocation, veil::client::AutoLock::lock, m_storageMappingLock, m_storageMapping, veil::client::locationInfo::storageId, veil::client::locationInfo::fileId.
string veil::client::StorageMapper::findLocation(std::string logicalName)
Query cluster about file location and instert it to cache.
StorageMapper::addLocation
References m_fslogic, addLocation.
Referenced by getLocationInfo, runTask.
void veil::client::StorageMapper::addLocation(std::string logicalName, protocol::fuse_messages::FileLocation location)
Cache given file location.
Insert to file location cache new FileLocation received from cluster.
References veil::client::locationInfo::validTo, veil::client::storageInfo::last_updated, veil::client::storageInfo::storageHelperName, veil::client::storageInfo::storageHelperArgs, m_fileMappingLock, veil::client::WRITE_LOCK, m_fileMapping, m_storageMappingLock, m_storageMapping, veil::client::VeilFS::getScheduler, veil::client::ISchedulable::TASK_REMOVE_EXPIRED_LOCATON_MAPPING, RENEW_LOCATION_MAPPING_TIME, veil::client::ISchedulable::TASK_RENEW_LOCATION_MAPPING.
Referenced by findLocation.
void veil::client::StorageMapper::openFile(std::string logicalName)
Increases open file count for specified file.
locationInfo::opened
References m_fileMappingLock, veil::client::WRITE_LOCK, m_fileMapping.
void veil::client::StorageMapper::releaseFile(std::string logicalName)
Decreases open file count for specified file.
locationInfo::opened
References m_fileMappingLock, veil::client::WRITE_LOCK, m_fileMapping, veil::client::VeilFS::getScheduler, m_fslogic, veil::client::ISchedulable::TASK_SEND_FILE_NOT_USED.
bool veil::client::StorageMapper::runTask(TaskID taskId, std::string arg0, std::string arg1, std::string arg3)
Task runner derived from ISchedulable.
ISchedulable::runTask
References m_fileMappingLock, veil::client::WRITE_LOCK, veil::client::ISchedulable::TASK_REMOVE_EXPIRED_LOCATON_MAPPING, m_fileMapping, veil::client::VeilFS::getScheduler, veil::client::ISchedulable::TASK_RENEW_LOCATION_MAPPING, m_fslogic, veil::client::ISchedulable::TASK_ASYNC_GET_FILE_LOCATION, findLocation.