fmemopen.c
typedef struct fmem fmem_t
static int readfn(void *handler, char *buf, int size)
References fmem::size, fmem::pos, fmem::buffer.
Referenced by fmemopen.
static int writefn(void *handler, const char *buf, int size)
References fmem::size, fmem::pos, fmem::buffer.
Referenced by fmemopen.
static fpos_t seekfn(void *handler, fpos_t offset, int whence)
References fmem::pos, fmem::size.
Referenced by fmemopen.
static int closefn(void *handler)
Referenced by fmemopen.
FILE* fmemopen(void *buf, size_t size, const char *mode)
A BSD port of the fmemopen Linux method using funopen.
man docs for fmemopen: http://linux.die.net/man/3/fmemopenman docs for funopen: https://developer.apple.com/library/mac/#documentation/Darwin/Reference/ManPages/man3/funopen.3.htmlThis method is ported from ingenuitas' python-tesseract project.You must call fclose on the returned file pointer or memory will be leaked. @param buf The data that will be used to back the FILE* methods. Must be at least @c size bytes. @param size The size of the @c buf data. @param mode The permitted stream operation modes. @returns A pointer that can be used in the fread/fwrite/fseek/fclose family of methods. If a failure occurred NULL will be returned.
References fmem::size, fmem::buffer, readfn, writefn, seekfn, closefn.