grid_proxy_init.c
SHORT_USAGE_FORMAT
args_show_short_help
args_show_full_usage
Referenced by proxy_init.
args_error_message
args_error
Referenced by proxy_init.
args_verify_next
Referenced by proxy_init.
int quiet
Referenced by proxy_init, globus_i_gsi_proxy_utils_key_gen_callback.
int debug
Referenced by proxy_init, globus_i_gsi_proxy_utils_key_gen_callback.
FILE* vout
stdout and stderr substitutions used in grid-proxy-utils
Referenced by proxy_info, proxy_init, globus_i_gsi_proxy_utils_key_gen_callback.
FILE* verr
Referenced by proxy_info, proxy_init, globus_i_gsi_proxy_utils_print_error.
char const* certPasswd
Referenced by proxy_init, globus_i_gsi_proxy_utils_pwstdin_callback.
int passwdLen
Referenced by proxy_init, globus_i_gsi_proxy_utils_pwstdin_callback.
char* LONG_USAGE
int globus_i_gsi_proxy_utils_print_error(globus_result_t result, int debug, const char *filename, int line, const char *fmt,...)
References verr.
Referenced by proxy_init.
static int globus_i_gsi_proxy_utils_pwstdin_callback(char *buf, int num, int w)
References passwdLen, certPasswd.
Referenced by proxy_init.
static void globus_i_gsi_proxy_utils_key_gen_callback(int p, int n, void *dummy)
References quiet, debug, vout.
Referenced by proxy_init.
static int globus_l_gsi_proxy_utils_extension_callback(globus_gsi_callback_data_t callback_data, X509_EXTENSION *extension)
Referenced by proxy_init.
int proxy_init(int argc, char **argv, FILE *_vout, FILE *_verr, char const *_pass, int _passLen)
This function replaces standard "main" of grid-proxy-init tool.
First two arguments are standard "main's" arugments. The others are used to capture standard output and standard error steams and pass cached certificate passphrase.
References vout, verr, certPasswd, passwdLen, args_error, args_show_full_usage, args_verify_next, debug, quiet, globus_i_gsi_proxy_utils_pwstdin_callback, globus_i_gsi_proxy_utils_print_error, globus_i_gsi_proxy_utils_key_gen_callback, GLOBUS_STDIO_UI_MODULE, globus_l_gsi_proxy_utils_extension_callback.