veil::client::utils
std::string veil::client::utils::toString(T in)
References in.
Referenced by veil::client::VeilFS::utime, veil::client::VeilFS::open, veil::client::VeilFS::opendir, veil::client::VeilFS::runTask.
T veil::client::utils::fromString(std::string in)