veil::client::gsi
bool veil::client::gsi::debug
Referenced by proxy_info, validateProxyCert, getProxyCertPath, main.
bool veil::client::gsi::validateProxyConfig()
References validateProxyCert.
Referenced by main.
bool veil::client::gsi::validateProxyCert()
References debug, PEER_CERTIFICATE_FILE_OPT, findUserCert, findUserKey, PROXY_INFO, X509_USER_CERT_ENV, GLOBUS_PEM_CERT_PATH, GLOBUS_P12_PATH, X509_USER_KEY_ENV, GLOBUS_PEM_KEY_PATH, CRYPTO_FREE, MSG_DEBUG_INFO, PROXY_INIT.
Referenced by validateProxyConfig, main.
string veil::client::gsi::getProxyCertPath()
References debug, PEER_CERTIFICATE_FILE_OPT, PROXY_INFO.
Referenced by main.
std::string veil::client::gsi::getClusterHostname()
References CLUSTER_HOSTNAME_OPT, PROXY_INFO, BASE_DOMAIN.
Referenced by main.
string veil::client::gsi::findUserCert()
References X509_USER_CERT_ENV, GLOBUS_PEM_CERT_PATH, GLOBUS_P12_PATH.
Referenced by validateProxyCert.
string veil::client::gsi::findUserKey()
References X509_USER_KEY_ENV, GLOBUS_PEM_KEY_PATH, GLOBUS_P12_PATH.
Referenced by validateProxyCert.