veilFuse.cc
boost::shared_ptr<VeilFS> VeilAppObject
Main application object (filesystem state)
Referenced by wrap_access, wrap_getattr, wrap_readlink, wrap_mknod, wrap_mkdir, wrap_unlink, wrap_rmdir, wrap_symlink, wrap_rename, wrap_link, wrap_chmod, wrap_chown, wrap_truncate, wrap_utime, wrap_open, wrap_read, wrap_write, wrap_statfs, wrap_flush, wrap_release, wrap_fsync, wrap_readdir, wrap_opendir, wrap_releasedir, wrap_fsyncdir, main.
struct fuse_operations vfs_oper
Referenced by oper_init, main.
static int wrap_access(const char *path, int mask)
References VeilAppObject.
Referenced by oper_init.
static int wrap_getattr(const char *path, struct stat *statbuf)
References VeilAppObject.
Referenced by oper_init.
static int wrap_readlink(const char *path, char *link, size_t size)
References VeilAppObject.
Referenced by oper_init.
static int wrap_mknod(const char *path, mode_t mode, dev_t dev)
References VeilAppObject.
Referenced by oper_init.
static int wrap_mkdir(const char *path, mode_t mode)
References VeilAppObject.
Referenced by oper_init.
static int wrap_unlink(const char *path)
References VeilAppObject.
Referenced by oper_init.
static int wrap_rmdir(const char *path)
References VeilAppObject.
Referenced by oper_init.
static int wrap_symlink(const char *path, const char *link)
References VeilAppObject.
Referenced by oper_init.
static int wrap_rename(const char *path, const char *newpath)
References VeilAppObject.
Referenced by oper_init.
static int wrap_link(const char *path, const char *newpath)
References VeilAppObject.
Referenced by oper_init.
static int wrap_chmod(const char *path, mode_t mode)
References VeilAppObject.
Referenced by oper_init.
static int wrap_chown(const char *path, uid_t uid, gid_t gid)
References VeilAppObject.
Referenced by oper_init.
static int wrap_truncate(const char *path, off_t newSize)
References VeilAppObject.
Referenced by oper_init.
static int wrap_utime(const char *path, struct utimbuf *ubuf)
References VeilAppObject.
Referenced by oper_init.
static int wrap_open(const char *path, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_read(const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_write(const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_statfs(const char *path, struct statvfs *statInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_flush(const char *path, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_release(const char *path, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_fsync(const char *path, int datasync, struct fuse_file_info *fi)
References VeilAppObject.
Referenced by oper_init.
static int wrap_readdir(const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_opendir(const char *path, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_releasedir(const char *path, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int wrap_fsyncdir(const char *path, int datasync, struct fuse_file_info *fileInfo)
References VeilAppObject.
Referenced by oper_init.
static int vfs_opt_proc(void *data, const char *arg, int key, struct fuse_args *outargs)
References CONFIG_ARGV_OPT_NAME.
Referenced by main.
static void oper_init()
References vfs_oper, wrap_getattr, wrap_access, wrap_readlink, wrap_readdir, wrap_mknod, wrap_mkdir, wrap_symlink, wrap_unlink, wrap_rmdir, wrap_rename, wrap_link, wrap_chmod, wrap_chown, wrap_truncate, wrap_open, wrap_read, wrap_write, wrap_statfs, wrap_release, wrap_fsync, wrap_utime, wrap_flush, wrap_opendir, wrap_releasedir, wrap_fsyncdir.
Referenced by fuse_init.
static void fuse_init()
References oper_init.
Referenced by main.
int main(int argc, char *argv[], char *envp[])
References fuse_init, vfs_opt_proc, debug, CONFIG_ARGV_OPT_NAME, GLOBAL_CONFIG_FILE, LOG_DIR_OPT, vfs_oper, veil::client::gsi::validateProxyConfig, veil::client::gsi::getProxyCertPath, veil::client::gsi::getClusterHostname, CLUSTER_PORT_OPT, veil::client::gsi::validateProxyCert, ALIVE_META_CONNECTIONS_COUNT_OPT, ALIVE_DATA_CONNECTIONS_COUNT_OPT, JOBSCHEDULER_THREADS_OPT, VeilAppObject.