##
## Export all variables to sub-invocation
##
export

bootstrap:
	mkdir -p $(PKG_ID)/debian
	cd $(PKG_ID)/debian && ../node_package/rebar -v create \
                              template_dir=../node_package/priv/templates \
                              template_vars=../$(PKG_VARS_CONFIG) template=deb
	make -C $(PKG_ID) -f debian/Makefile
