
##
## Export all variables to sub-invocation
##
export

bootstrap:
	mkdir -p $(PKG_ID)/fbsdng
	cd $(PKG_ID)/fbsdng && ../node_package/rebar -v create \
                                template_dir=../node_package/priv/templates \
                                template_vars=../$(PKG_VARS_CONFIG) template=fbsdng
	$(MAKE) -C $(PKG_ID) -f fbsdng/Makefile
