%% directories to be compiled
{'*', [{outdir, "."}, {i, "../include"}]}.
{'example/*', [{outdir, "./example"}]}.
{'nodes_monitoring_and_workers_test/*', [{outdir, "./nodes_monitoring_and_workers_test"}, {i, "../include"}]}.